[project]
name = "minorityprompt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gdown>=5.2.1",
    "pandas>=2.3.3",
]
